2018-04-14 00:08:32,820 ERROR 47250 [-/127.0.0.1/-/13ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47250
hostname: loveRain.local

2018-04-14 00:08:33,746 ERROR 47250 [-/127.0.0.1/-/2ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47250
hostname: loveRain.local

2018-04-14 00:08:34,623 ERROR 47250 [-/127.0.0.1/-/1ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47250
hostname: loveRain.local

2018-04-14 00:08:35,254 ERROR 47250 [-/127.0.0.1/-/1ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47250
hostname: loveRain.local

2018-04-14 00:08:35,814 ERROR 47250 [-/127.0.0.1/-/0ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47250
hostname: loveRain.local

2018-04-14 00:08:36,390 ERROR 47250 [-/127.0.0.1/-/1ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47250
hostname: loveRain.local

2018-04-14 00:19:06,710 ERROR 47636 [-/127.0.0.1/-/14ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47636
hostname: loveRain.local

2018-04-14 00:19:07,920 ERROR 47636 [-/127.0.0.1/-/1ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47636
hostname: loveRain.local

2018-04-14 00:19:08,552 ERROR 47636 [-/127.0.0.1/-/1ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47636
hostname: loveRain.local

2018-04-14 00:19:08,971 ERROR 47636 [-/127.0.0.1/-/1ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47636
hostname: loveRain.local

2018-04-14 00:19:09,223 ERROR 47636 [-/127.0.0.1/-/0ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47636
hostname: loveRain.local

2018-04-14 00:19:09,964 ERROR 47636 [-/127.0.0.1/-/1ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47636
hostname: loveRain.local

2018-04-14 00:19:10,536 ERROR 47636 [-/127.0.0.1/-/1ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47636
hostname: loveRain.local

2018-04-14 00:19:11,064 ERROR 47636 [-/127.0.0.1/-/1ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47636
hostname: loveRain.local

2018-04-14 00:19:11,522 ERROR 47636 [-/127.0.0.1/-/1ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.TypeError: Cannot read property 'insert' of undefined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:35:37)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 47636
hostname: loveRain.local

2018-04-14 12:00:55,554 ERROR 47635 nodejs.ClusterClientNoResponseError: client no response in 41753828ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 47635
hostname: loveRain.local

2018-04-14 15:59:41,277 ERROR 52588 [-/127.0.0.1/-/56ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user_vercode`(`phone`, `code`, `time`) VALUES('17334071590', '475340', 1523692781237)
code: 'ER_NO_DEFAULT_FOR_FIELD'
errno: 1364
sqlMessage: 'Field \'id\' doesn\'t have a default value'
sqlState: 'HY000'
index: 0
sql: 'INSERT INTO `cd_user_vercode`(`phone`, `code`, `time`) VALUES(\'17334071590\', \'475340\', 1523692781237)'
name: 'ER_NO_DEFAULT_FOR_FIELDError'
pid: 52588
hostname: loveRain.local

2018-04-14 16:00:25,400 ERROR 52588 [-/127.0.0.1/-/7ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user_vercode`(`phone`, `code`, `time`) VALUES('17334071590', '478207', 1523692825394)
code: 'ER_NO_DEFAULT_FOR_FIELD'
errno: 1364
sqlMessage: 'Field \'id\' doesn\'t have a default value'
sqlState: 'HY000'
index: 0
sql: 'INSERT INTO `cd_user_vercode`(`phone`, `code`, `time`) VALUES(\'17334071590\', \'478207\', 1523692825394)'
name: 'ER_NO_DEFAULT_FOR_FIELDError'
pid: 52588
hostname: loveRain.local

2018-04-14 16:00:44,068 ERROR 52712 [-/127.0.0.1/-/30ms GET /api?interface=vercode&phone=17334071590&type=1] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user_vercode`(`phone`, `code`, `time`) VALUES('17334071590', '883665', 1523692844047)
code: 'ER_NO_DEFAULT_FOR_FIELD'
errno: 1364
sqlMessage: 'Field \'id\' doesn\'t have a default value'
sqlState: 'HY000'
index: 0
sql: 'INSERT INTO `cd_user_vercode`(`phone`, `code`, `time`) VALUES(\'17334071590\', \'883665\', 1523692844047)'
name: 'ER_NO_DEFAULT_FOR_FIELDError'
pid: 52712
hostname: loveRain.local

2018-04-14 16:26:43,317 ERROR 53652 [-/127.0.0.1/-/22ms GET /api?interface=register&phone=17334071590&code=123&password=123456] nodejs.ReferenceError: ctx is not defined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:22:28)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 53652
hostname: loveRain.local

2018-04-14 16:30:40,981 ERROR 53898 [-/127.0.0.1/-/28ms GET /api?interface=register&phone=17334071590&code=123&password=123456] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'credit.posts' doesn't exist
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: SELECT * FROM `posts` WHERE `id` = '17334071590' LIMIT 0, 1
code: 'ER_NO_SUCH_TABLE'
errno: 1146
sqlMessage: 'Table \'credit.posts\' doesn\'t exist'
sqlState: '42S02'
index: 0
sql: 'SELECT * FROM `posts` WHERE `id` = \'17334071590\' LIMIT 0, 1'
name: 'ER_NO_SUCH_TABLEError'
pid: 53898
hostname: loveRain.local

2018-04-14 16:30:50,475 ERROR 53898 [-/127.0.0.1/-/4ms GET /api?interface=register&phone=17334071590&code=123&password=123456] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'credit.posts' doesn't exist
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: SELECT * FROM `posts` WHERE `id` = '17334071590' LIMIT 0, 1
code: 'ER_NO_SUCH_TABLE'
errno: 1146
sqlMessage: 'Table \'credit.posts\' doesn\'t exist'
sqlState: '42S02'
index: 0
sql: 'SELECT * FROM `posts` WHERE `id` = \'17334071590\' LIMIT 0, 1'
name: 'ER_NO_SUCH_TABLEError'
pid: 53898
hostname: loveRain.local

2018-04-14 16:30:52,153 ERROR 53911 [-/127.0.0.1/-/23ms GET /api?interface=register&phone=17334071590&code=123&password=123456] nodejs.TypeError: Cannot read property 'serverStatus' of null
    at mysql.getVercode (/Users/chz/Desktop/credit/app/service/mysql.js:21:22)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 53911
hostname: loveRain.local

2018-04-14 16:51:30,927 ERROR 55185 [-/127.0.0.1/-/17ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '17334071590' for key 'name_UNIQUE'
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES('17334071590', 'werwer', 1523695890910)
code: 'ER_DUP_ENTRY'
errno: 1062
sqlMessage: 'Duplicate entry \'17334071590\' for key \'name_UNIQUE\''
sqlState: '23000'
index: 0
sql: 'INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES(\'17334071590\', \'werwer\', 1523695890910)'
name: 'ER_DUP_ENTRYError'
pid: 55185
hostname: loveRain.local

2018-04-14 16:54:34,174 ERROR 55293 [-/127.0.0.1/-/29ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '17334071590' for key 'name_UNIQUE'
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES('17334071590', 'werwer', 1523696074151)
code: 'ER_DUP_ENTRY'
errno: 1062
sqlMessage: 'Duplicate entry \'17334071590\' for key \'name_UNIQUE\''
sqlState: '23000'
index: 0
sql: 'INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES(\'17334071590\', \'werwer\', 1523696074151)'
name: 'ER_DUP_ENTRYError'
pid: 55293
hostname: loveRain.local

2018-04-14 16:54:34,986 ERROR 55293 [-/127.0.0.1/-/14ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '17334071590' for key 'name_UNIQUE'
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES('17334071590', 'werwer', 1523696074973)
code: 'ER_DUP_ENTRY'
errno: 1062
sqlMessage: 'Duplicate entry \'17334071590\' for key \'name_UNIQUE\''
sqlState: '23000'
index: 0
sql: 'INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES(\'17334071590\', \'werwer\', 1523696074973)'
name: 'ER_DUP_ENTRYError'
pid: 55293
hostname: loveRain.local

2018-04-14 16:54:35,628 ERROR 55293 [-/127.0.0.1/-/13ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '17334071590' for key 'name_UNIQUE'
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES('17334071590', 'werwer', 1523696075615)
code: 'ER_DUP_ENTRY'
errno: 1062
sqlMessage: 'Duplicate entry \'17334071590\' for key \'name_UNIQUE\''
sqlState: '23000'
index: 0
sql: 'INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES(\'17334071590\', \'werwer\', 1523696075615)'
name: 'ER_DUP_ENTRYError'
pid: 55293
hostname: loveRain.local

2018-04-14 16:54:47,272 ERROR 55311 [-/127.0.0.1/-/36ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '17334071590' for key 'name_UNIQUE'
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES('17334071590', 'werwer', 1523696087244)
code: 'ER_DUP_ENTRY'
errno: 1062
sqlMessage: 'Duplicate entry \'17334071590\' for key \'name_UNIQUE\''
sqlState: '23000'
index: 0
sql: 'INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES(\'17334071590\', \'werwer\', 1523696087244)'
name: 'ER_DUP_ENTRYError'
pid: 55311
hostname: loveRain.local

2018-04-14 16:54:47,964 ERROR 55311 [-/127.0.0.1/-/13ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '17334071590' for key 'name_UNIQUE'
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES('17334071590', 'werwer', 1523696087951)
code: 'ER_DUP_ENTRY'
errno: 1062
sqlMessage: 'Duplicate entry \'17334071590\' for key \'name_UNIQUE\''
sqlState: '23000'
index: 0
sql: 'INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES(\'17334071590\', \'werwer\', 1523696087951)'
name: 'ER_DUP_ENTRYError'
pid: 55311
hostname: loveRain.local

2018-04-14 16:58:05,171 ERROR 55522 [-/127.0.0.1/-/13ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ReferenceError: number is not defined
    at mysql.addUser (/Users/chz/Desktop/credit/app/service/mysql.js:13:79)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:27:53)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 55522
hostname: loveRain.local

2018-04-14 16:58:15,768 ERROR 55522 [-/127.0.0.1/-/3ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ReferenceError: number is not defined
    at mysql.addUser (/Users/chz/Desktop/credit/app/service/mysql.js:13:79)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:27:53)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 55522
hostname: loveRain.local

2018-04-14 17:29:32,680 ERROR 56501 [-/127.0.0.1/-/19ms GET /api?interface=login&account=17334071590&password=werwer] nodejs.ReferenceError: result is not defined
    at mysql.login (/Users/chz/Desktop/credit/app/service/mysql.js:44:83)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 56501
hostname: loveRain.local

2018-04-14 17:30:06,904 ERROR 56539 [-/127.0.0.1/-/13ms GET /api?interface=login&account=17334071590&password=werwer] nodejs.ReferenceError: result is not defined
    at mysql.login (/Users/chz/Desktop/credit/app/service/mysql.js:44:83)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 56539
hostname: loveRain.local

2018-04-14 17:30:24,599 ERROR 56539 [-/127.0.0.1/-/14ms GET /api?interface=login&account=17334071590&password=werwer] nodejs.ReferenceError: result is not defined
    at mysql.login (/Users/chz/Desktop/credit/app/service/mysql.js:44:83)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 56539
hostname: loveRain.local

2018-04-14 17:42:27,178 ERROR 56867 [-/127.0.0.1/-/38ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ReferenceError: findUser is not defined
    at mysql.addUser (/Users/chz/Desktop/credit/app/service/mysql.js:13:32)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:37:53)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 56867
hostname: loveRain.local

2018-04-14 17:42:44,166 ERROR 56901 [-/127.0.0.1/-/36ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '17334071590' for key 'name_UNIQUE'
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES('17334071590', 'werwer', 1523698964144)
code: 'ER_DUP_ENTRY'
errno: 1062
sqlMessage: 'Duplicate entry \'17334071590\' for key \'name_UNIQUE\''
sqlState: '23000'
index: 0
sql: 'INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES(\'17334071590\', \'werwer\', 1523698964144)'
name: 'ER_DUP_ENTRYError'
pid: 56901
hostname: loveRain.local

2018-04-14 17:43:39,624 ERROR 56901 [-/127.0.0.1/-/117ms GET /api?interface=register&phone=17334071590&code=617826&password=werwer] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '17334071590' for key 'name_UNIQUE'
    at Query.Sequence._packetToError (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/chz/Desktop/credit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chz/Desktop/credit/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (/Users/chz/Desktop/credit/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at Pool.<anonymous> (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/chz/Desktop/credit/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/chz/Desktop/credit/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/chz/Desktop/credit/node_modules/co/index.js:65:19)
    at /Users/chz/Desktop/credit/node_modules/co/index.js:54:5
    at RDSClient.co (/Users/chz/Desktop/credit/node_modules/co/index.js:50:10)
    sql: INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES('17334071590', 'werwer', 1523699019512)
code: 'ER_DUP_ENTRY'
errno: 1062
sqlMessage: 'Duplicate entry \'17334071590\' for key \'name_UNIQUE\''
sqlState: '23000'
index: 0
sql: 'INSERT INTO `cd_user`(`name`, `key`, `time`) VALUES(\'17334071590\', \'werwer\', 1523699019512)'
name: 'ER_DUP_ENTRYError'
pid: 56901
hostname: loveRain.local

2018-04-14 18:11:46,985 ERROR 58150 [-/127.0.0.1/-/32ms GET /api?interface=forget&phone=17334071590&password=fjweiofjoewifjwe&code=617826] nodejs.TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:363:11)
    at respond (/Users/chz/Desktop/credit/node_modules/koa/lib/application.js:246:25)
    at handleResponse (/Users/chz/Desktop/credit/node_modules/koa/lib/application.js:148:34)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 58150
hostname: loveRain.local

2018-04-14 21:00:09,090 ERROR 56393 nodejs.ClusterClientNoResponseError: client no response in 3582097ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 56393
hostname: loveRain.local

2018-04-14 22:14:33,246 ERROR 61068 nodejs.ClusterClientNoResponseError: client no response in 1581218ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 61068
hostname: loveRain.local

2018-04-14 23:56:38,757 ERROR 64705 [-/127.0.0.1/-/31ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.ReferenceError: jsonResult is not defined
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:63:22)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 64705
hostname: loveRain.local

2018-04-14 23:57:21,471 ERROR 64782 nodejs.ReferenceError: result is not defined
    at ApiController.jsonResult (/Users/chz/Desktop/credit/app/controller/api.js:148:18)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:63:27)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 64782
hostname: loveRain.local

2018-04-14 23:57:22,965 ERROR 64782 nodejs.ReferenceError: result is not defined
    at ApiController.jsonResult (/Users/chz/Desktop/credit/app/controller/api.js:148:18)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:63:27)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 64782
hostname: loveRain.local

2018-04-14 23:57:29,267 ERROR 64782 nodejs.ReferenceError: result is not defined
    at ApiController.jsonResult (/Users/chz/Desktop/credit/app/controller/api.js:148:18)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:63:27)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 64782
hostname: loveRain.local

2018-04-14 23:57:29,932 ERROR 64794 [-/127.0.0.1/-/30ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.ReferenceError: result is not defined
    at ApiController.jsonResult (/Users/chz/Desktop/credit/app/controller/api.js:148:18)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:63:33)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 64794
hostname: loveRain.local

2018-04-14 23:57:30,273 ERROR 64794 [-/127.0.0.1/-/3ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.ReferenceError: result is not defined
    at ApiController.jsonResult (/Users/chz/Desktop/credit/app/controller/api.js:148:18)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:63:33)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 64794
hostname: loveRain.local

2018-04-14 23:57:44,772 ERROR 64794 [-/127.0.0.1/-/5ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.ReferenceError: result is not defined
    at ApiController.jsonResult (/Users/chz/Desktop/credit/app/controller/api.js:148:18)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:63:33)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 64794
hostname: loveRain.local

2018-04-15 00:05:00,672 ERROR 65072 [-/127.0.0.1/-/12ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.ReferenceError: reqMap is not defined
    at ApiController.ApiForget (/Users/chz/Desktop/credit/app/controller/api.js:108:20)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:57:18)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 65072
hostname: loveRain.local

2018-04-15 00:05:35,934 ERROR 65072 [-/127.0.0.1/-/5ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.ReferenceError: reqMap is not defined
    at ApiController.ApiForget (/Users/chz/Desktop/credit/app/controller/api.js:108:20)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:57:18)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 65072
hostname: loveRain.local

2018-04-15 00:05:36,867 ERROR 65072 [-/127.0.0.1/-/3ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.ReferenceError: reqMap is not defined
    at ApiController.ApiForget (/Users/chz/Desktop/credit/app/controller/api.js:108:20)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:57:18)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 65072
hostname: loveRain.local

2018-04-15 00:07:11,408 ERROR 65153 [-/127.0.0.1/-/8ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.TypeError: Cannot read property 'phone' of undefined
    at ApiController.ApiForget (/Users/chz/Desktop/credit/app/controller/api.js:109:26)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:57:18)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 65153
hostname: loveRain.local

2018-04-15 00:07:11,653 ERROR 65153 [-/127.0.0.1/-/2ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.TypeError: Cannot read property 'phone' of undefined
    at ApiController.ApiForget (/Users/chz/Desktop/credit/app/controller/api.js:109:26)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:57:18)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 65153
hostname: loveRain.local

2018-04-15 00:07:11,868 ERROR 65153 [-/127.0.0.1/-/1ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.TypeError: Cannot read property 'phone' of undefined
    at ApiController.ApiForget (/Users/chz/Desktop/credit/app/controller/api.js:109:26)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:57:18)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 65153
hostname: loveRain.local

2018-04-15 00:07:12,085 ERROR 65153 [-/127.0.0.1/-/1ms GET /api?interface=forget&phone=173342071590&password=fjweiofjoewifjwe&code=617826] nodejs.TypeError: Cannot read property 'phone' of undefined
    at ApiController.ApiForget (/Users/chz/Desktop/credit/app/controller/api.js:109:26)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:57:18)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 65153
hostname: loveRain.local

2018-04-15 01:02:23,141 ERROR 977 [-/127.0.0.1/-/6ms GET /api?interface=login&account=18331004424&password=werwer] nodejs.ReferenceError: number is not defined
    at ApiController.ApiLogin (/Users/chz/Desktop/credit/app/controller/api.js:43:53)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:22:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 977
hostname: loveRain.local

2018-04-15 01:04:11,159 ERROR 1111 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
2018-04-15 12:34:16,044 ERROR 974 nodejs.ClusterClientNoResponseError: client no response in 39629835ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 974
hostname: loveRain.local

2018-04-15 12:42:08,688 ERROR 974 nodejs.ClusterClientNoResponseError: client no response in 171551ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 974
hostname: loveRain.local

2018-04-15 13:16:20,004 ERROR 3849 [-/127.0.0.1/-/21ms GET /api?interface=login&account=18331004424&password=890809] nodejs.TypeError: Cannot read property 'reponse' of undefined
    at ApiController.ApiLogin (/Users/chz/Desktop/credit/app/controller/api.js:54:27)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 3849
hostname: loveRain.local

2018-04-15 13:16:47,384 ERROR 3849 [-/127.0.0.1/-/17ms GET /api?interface=login&account=18331004424&password=890809] nodejs.TypeError: Cannot read property 'reponse' of undefined
    at ApiController.ApiLogin (/Users/chz/Desktop/credit/app/controller/api.js:54:27)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 3849
hostname: loveRain.local

2018-04-15 13:17:37,432 ERROR 3947 [-/127.0.0.1/-/20ms GET /api?interface=login&account=18331004424&password=890809] nodejs.TypeError: Cannot read property 'set' of undefined
    at ApiController.ApiLogin (/Users/chz/Desktop/credit/app/controller/api.js:51:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 3947
hostname: loveRain.local

2018-04-15 13:32:00,528 ERROR 4239 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
2018-04-15 13:40:55,346 ERROR 4825 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
2018-04-15 15:41:05,885 ERROR 6748 [-/127.0.0.1/-/33ms GET /api?interface=login&account=17334071590&password=123456] nodejs.ReferenceError: ms is not defined
    at ApiController.ApiLogin (/Users/chz/Desktop/credit/app/controller/api.js:54:28)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 6748
hostname: loveRain.local

2018-04-15 15:42:41,239 ERROR 6748 [-/127.0.0.1/-/23ms GET /api?interface=login&account=17334071590&password=123456] nodejs.ReferenceError: ms is not defined
    at ApiController.ApiLogin (/Users/chz/Desktop/credit/app/controller/api.js:54:28)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 6748
hostname: loveRain.local

2018-04-15 16:10:52,681 ERROR 8179 [-/127.0.0.1/-/16ms GET /api?interface=score&phone=18331004424] nodejs.TypeError: Cannot read property 'length' of undefined
    at ApiController.isLogin (/Users/chz/Desktop/credit/app/controller/api.js:167:27)
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:155:33)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:33:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16

pid: 8179
hostname: loveRain.local

2018-04-15 16:10:53,533 ERROR 8179 [-/127.0.0.1/-/4ms GET /api?interface=score&phone=18331004424] nodejs.TypeError: Cannot read property 'length' of undefined
    at ApiController.isLogin (/Users/chz/Desktop/credit/app/controller/api.js:167:27)
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:155:33)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:33:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16

pid: 8179
hostname: loveRain.local

2018-04-15 16:25:19,166 ERROR 8816 [-/127.0.0.1/-/15ms GET /api?interface=score&phone=17334071590] nodejs.ReferenceError: tx is not defined
    at ApiController.isLogin (/Users/chz/Desktop/credit/app/controller/api.js:167:16)
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:155:33)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:33:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16

pid: 8816
hostname: loveRain.local

2018-04-15 16:25:28,389 ERROR 8816 [-/127.0.0.1/-/4ms GET /api?interface=score&phone=17334071590] nodejs.ReferenceError: tx is not defined
    at ApiController.isLogin (/Users/chz/Desktop/credit/app/controller/api.js:167:16)
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:155:33)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:33:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16

pid: 8816
hostname: loveRain.local

2018-04-15 16:25:29,491 ERROR 8816 [-/127.0.0.1/-/1ms GET /api?interface=score&phone=17334071590] nodejs.ReferenceError: tx is not defined
    at ApiController.isLogin (/Users/chz/Desktop/credit/app/controller/api.js:167:16)
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:155:33)
    at ApiController.index (/Users/chz/Desktop/credit/app/controller/api.js:33:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/chz/Desktop/credit/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/chz/Desktop/credit/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/chz/Desktop/credit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/chz/Desktop/credit/node_modules/koa-router/lib/router.js:346:16

pid: 8816
hostname: loveRain.local

2018-04-15 17:52:59,980 ERROR 11471 [-/127.0.0.1/-/21ms GET /api?interface=score] nodejs.TypeError: ctx.service.mysql.getCreditScore is not a function
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:160:44)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 11471
hostname: loveRain.local

2018-04-15 17:53:28,685 ERROR 11471 [-/127.0.0.1/-/14ms GET /api?interface=score] nodejs.TypeError: ctx.service.mysql.getCreditScore is not a function
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:160:44)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 11471
hostname: loveRain.local

2018-04-15 17:53:56,324 ERROR 11530 [-/127.0.0.1/-/24ms GET /api?interface=score] nodejs.ReferenceError: number is not defined
    at mysql.getUserScore (/Users/chz/Desktop/credit/app/service/mysql.js:85:34)
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:160:44)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 11530
hostname: loveRain.local

2018-04-15 17:54:09,950 ERROR 11530 [-/127.0.0.1/-/8ms GET /api?interface=score] nodejs.ReferenceError: number is not defined
    at mysql.getUserScore (/Users/chz/Desktop/credit/app/service/mysql.js:85:34)
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:160:44)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 11530
hostname: loveRain.local

2018-04-15 17:54:10,874 ERROR 11530 [-/127.0.0.1/-/4ms GET /api?interface=score] nodejs.ReferenceError: number is not defined
    at mysql.getUserScore (/Users/chz/Desktop/credit/app/service/mysql.js:85:34)
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:160:44)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 11530
hostname: loveRain.local

2018-04-15 17:54:11,892 ERROR 11530 [-/127.0.0.1/-/22ms GET /api?interface=score] nodejs.ReferenceError: number is not defined
    at mysql.getUserScore (/Users/chz/Desktop/credit/app/service/mysql.js:85:34)
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:160:44)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 11530
hostname: loveRain.local

2018-04-15 17:57:05,297 ERROR 11671 [-/127.0.0.1/-/24ms GET /api?interface=score] nodejs.ReferenceError: score is not defined
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:164:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 11671
hostname: loveRain.local

2018-04-15 17:57:19,812 ERROR 11671 [-/127.0.0.1/-/20ms GET /api?interface=score] nodejs.ReferenceError: score is not defined
    at ApiController.getCreditScore (/Users/chz/Desktop/credit/app/controller/api.js:164:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 11671
hostname: loveRain.local

2018-04-15 22:13:21,855 ERROR 17634 [-/127.0.0.1/-/10ms GET /api?interface=upload&type=1_1&image1=123&image2=456] nodejs.TypeError: Cannot create property 'userid' on string '1_1'
    at mysql.commitInfo (/Users/chz/Desktop/credit/app/service/mysql.js:241:34)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 17634
hostname: loveRain.local

